language: python
python:
  - "3.5"
  - "3.6"

install: "pip install -r requirements.txt"

# create test db
before_script:
  - psql -c 'create database test;' -U postgres

# command to run tests.py
script:
  - ./app/tests/test-travis.sh
